### ISSUE TITLE
STG SNMP v2

### ISSUE THREAD

**Issue by johngriegerjr** [riceball-k/stg-graph-plot#1]
Not an issue with your program. This is an issue I have with STG. I was wondering if you could help me with this. STG does not work with SNMP v2. When I perform a packet capture with Wireshark all of the snmp get requests are sent in v1 format. Do you know how to get STG to work with SNMP v2?

Google Translate:
プログラムの問題ではありません。 これは私がSTGで抱えている問題です。 私はあなたがこれで私を助けることができるかどうか疑問に思いました。 STGはSNMPv2では機能しません。 Wiresharkでパケットキャプチャを実行すると、すべてのsnmpgetリクエストがv1形式で送信されます。 STGをSNMPv2で動作させる方法を知っていますか？

**Comment by tadakawa** [comment]
I don't know how to send an SNMPv2c request from STG.
There was no description in the STG documentation (readme.txt) either.

**Comment by johngriegerjr** [comment]
Thank you for confirming. I wanted to check and make sure I was not missing something. The website where I downloaded STG from is misleading as it states the program works with SNMP v1 & 2c. http://leonidvm.chat.ru/ Thanks again!
